// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloClient interface {
	// UnaryAPI
	UnaryHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// SServerStreaming
	ServerStreamingHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Hello_ServerStreamingHelloClient, error)
	// ClientStreamingE
	ClientStreamingHello(ctx context.Context, opts ...grpc.CallOption) (Hello_ClientStreamingHelloClient, error)
	// BidirectionalStreaming
	BidirectionalStreamingHello(ctx context.Context, opts ...grpc.CallOption) (Hello_BidirectionalStreamingHelloClient, error)
}

type helloClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloClient(cc grpc.ClientConnInterface) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) UnaryHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Hello/UnaryHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloClient) ServerStreamingHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Hello_ServerStreamingHelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &Hello_ServiceDesc.Streams[0], "/helloworld.Hello/ServerStreamingHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloServerStreamingHelloClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Hello_ServerStreamingHelloClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type helloServerStreamingHelloClient struct {
	grpc.ClientStream
}

func (x *helloServerStreamingHelloClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloClient) ClientStreamingHello(ctx context.Context, opts ...grpc.CallOption) (Hello_ClientStreamingHelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &Hello_ServiceDesc.Streams[1], "/helloworld.Hello/ClientStreamingHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloClientStreamingHelloClient{stream}
	return x, nil
}

type Hello_ClientStreamingHelloClient interface {
	Send(*HelloRequest) error
	CloseAndRecv() (*HelloReply, error)
	grpc.ClientStream
}

type helloClientStreamingHelloClient struct {
	grpc.ClientStream
}

func (x *helloClientStreamingHelloClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloClientStreamingHelloClient) CloseAndRecv() (*HelloReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloClient) BidirectionalStreamingHello(ctx context.Context, opts ...grpc.CallOption) (Hello_BidirectionalStreamingHelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &Hello_ServiceDesc.Streams[2], "/helloworld.Hello/BidirectionalStreamingHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloBidirectionalStreamingHelloClient{stream}
	return x, nil
}

type Hello_BidirectionalStreamingHelloClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type helloBidirectionalStreamingHelloClient struct {
	grpc.ClientStream
}

func (x *helloBidirectionalStreamingHelloClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloBidirectionalStreamingHelloClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HelloServer is the server API for Hello service.
// All implementations must embed UnimplementedHelloServer
// for forward compatibility
type HelloServer interface {
	// UnaryAPI
	UnaryHello(context.Context, *HelloRequest) (*HelloReply, error)
	// SServerStreaming
	ServerStreamingHello(*HelloRequest, Hello_ServerStreamingHelloServer) error
	// ClientStreamingE
	ClientStreamingHello(Hello_ClientStreamingHelloServer) error
	// BidirectionalStreaming
	BidirectionalStreamingHello(Hello_BidirectionalStreamingHelloServer) error
	mustEmbedUnimplementedHelloServer()
}

// UnimplementedHelloServer must be embedded to have forward compatible implementations.
type UnimplementedHelloServer struct {
}

func (UnimplementedHelloServer) UnaryHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryHello not implemented")
}
func (UnimplementedHelloServer) ServerStreamingHello(*HelloRequest, Hello_ServerStreamingHelloServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerStreamingHello not implemented")
}
func (UnimplementedHelloServer) ClientStreamingHello(Hello_ClientStreamingHelloServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStreamingHello not implemented")
}
func (UnimplementedHelloServer) BidirectionalStreamingHello(Hello_BidirectionalStreamingHelloServer) error {
	return status.Errorf(codes.Unimplemented, "method BidirectionalStreamingHello not implemented")
}
func (UnimplementedHelloServer) mustEmbedUnimplementedHelloServer() {}

// UnsafeHelloServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloServer will
// result in compilation errors.
type UnsafeHelloServer interface {
	mustEmbedUnimplementedHelloServer()
}

func RegisterHelloServer(s grpc.ServiceRegistrar, srv HelloServer) {
	s.RegisterService(&Hello_ServiceDesc, srv)
}

func _Hello_UnaryHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).UnaryHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Hello/UnaryHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).UnaryHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hello_ServerStreamingHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HelloServer).ServerStreamingHello(m, &helloServerStreamingHelloServer{stream})
}

type Hello_ServerStreamingHelloServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type helloServerStreamingHelloServer struct {
	grpc.ServerStream
}

func (x *helloServerStreamingHelloServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Hello_ClientStreamingHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloServer).ClientStreamingHello(&helloClientStreamingHelloServer{stream})
}

type Hello_ClientStreamingHelloServer interface {
	SendAndClose(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type helloClientStreamingHelloServer struct {
	grpc.ServerStream
}

func (x *helloClientStreamingHelloServer) SendAndClose(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloClientStreamingHelloServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Hello_BidirectionalStreamingHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloServer).BidirectionalStreamingHello(&helloBidirectionalStreamingHelloServer{stream})
}

type Hello_BidirectionalStreamingHelloServer interface {
	Send(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type helloBidirectionalStreamingHelloServer struct {
	grpc.ServerStream
}

func (x *helloBidirectionalStreamingHelloServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloBidirectionalStreamingHelloServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Hello_ServiceDesc is the grpc.ServiceDesc for Hello service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hello_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnaryHello",
			Handler:    _Hello_UnaryHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStreamingHello",
			Handler:       _Hello_ServerStreamingHello_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientStreamingHello",
			Handler:       _Hello_ClientStreamingHello_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BidirectionalStreamingHello",
			Handler:       _Hello_BidirectionalStreamingHello_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "helloworld/helloworld.proto",
}
